version: '3'

services:
    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_container
        ports:
            - "8080:80"
        environment:
            - DB_HOST=mysql
            - REDIS_HOST=redis
        volumes:
            - .:/var/www/html

    mysql:
        image: mysql:5.7
        container_name: mysql_container
        environment:
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root_password
            - MYSQL_ROOT_PASSWORD=root_password
        ports:
            - "3306:3306"

    redis:
        image: redis:latest
        container_name: redis_container
        ports:
            - "6379:6379"
